# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17.1
    steps:
      - checkout

      - run:
          name: Run Tests
          command: |
            go test ./... -v -coverprofile=cover.out
            go tool cover -html=cover.out -o=result-cover.html
            go tool cover -func=cover.out > result-cover-func.out
            gotestsum --junitfile result-unit-tests.xml
      
      - run:
          name: Prepare Artifacts Dir and Test Reports
          command: |
            mkdir -p /tmp/artifacts
            mkdir -p /tmp/artifacts/test-results
            mv result-* /tmp/artifacts/test-results

      - run:
          name: Build
          command: |
            go build -a -v -o /tmp/artifacts/marvel .

      - store_artifacts:
          path: /tmp/artifacts

  publish-github-release:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17.1
    steps:
        - checkout
        - run: go get -u github.com/mitchellh/gox
        - run: go get -u github.com/tcnksm/ghr
        - run: go get -u github.com/stevenmatthewt/semantics
        - run:
            name: cross compile
            command: |
              gox -os="linux darwin windows" -arch="amd64" -output="dist/marvelcli_{{.OS}}_{{.Arch}}"
              cd dist/ && gzip * && pwd && ls -la
        - attach_workspace:
            at: ./artifacts
        - run:
            name: "publish release on GitHub"
            command: |
              tag=$(semantics --output-tag)
              echo $tag
              VERSION=$tag
              ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -n "Version ${VERSION}" ./artifacts

# Invoke jobs via workflows
workflows:
  marvel-api-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - init
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - init